Repository jv-cc/FlowMesh, pull requests merged in 2024-12, with the labels that each got.

#5 chore: hub 서비스 환경 초기 설정
  com.jv-cc.flowmesh.hub-server/.gitattributes
  com.jv-cc.flowmesh.hub-server/.gitignore
  com.jv-cc.flowmesh.hub-server/build.gradle
  com.jv-cc.flowmesh.hub-server/gradle/wrapper/gradle-wrapper.jar
  com.jv-cc.flowmesh.hub-server/gradle/wrapper/gradle-wrapper.properties
  com.jv-cc.flowmesh.hub-server/gradlew
  com.jv-cc.flowmesh.hub-server/gradlew.bat
  com.jv-cc.flowmesh.hub-server/settings.gradle
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/HubServerApplication.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/dto/ResDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/Error.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/HubException.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/model/HubEntity.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/repository/HubRepository.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/swagger/HubControllerSwagger.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/request/ReqHubPostDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/resources/application-dev.yml
  com.jv-cc.flowmesh.hub-server/src/main/resources/application.yml
  com.jv-cc.flowmesh.hub-server/src/test/java/com/jv_cc/flowmesh/hub_server/HubServerApplicationTests.java
Labels: 설정

#10 [#1] chore: 서비스 환경 초기 설정
  com.jv-cc.flowmesh.auth/.gitattributes
  com.jv-cc.flowmesh.auth/.gitignore
  com.jv-cc.flowmesh.auth/build.gradle
  com.jv-cc.flowmesh.auth/gradle/wrapper/gradle-wrapper.jar
  com.jv-cc.flowmesh.auth/gradle/wrapper/gradle-wrapper.properties
  com.jv-cc.flowmesh.auth/gradlew
  com.jv-cc.flowmesh.auth/gradlew.bat
  com.jv-cc.flowmesh.auth/settings.gradle
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/AuthApplication.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/ResDTO.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/AuthException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/Error.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/service/AuthService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/UserRoleEnum.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/repository/AuthRepository.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/infrastructor/swagger/AuthControllerSwagger.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/AuthController.java
  com.jv-cc.flowmesh.auth/src/main/resources/application-dev.yml
  com.jv-cc.flowmesh.auth/src/main/resources/application.yml
  com.jv-cc.flowmesh.auth/src/test/java/com/jv_cc/flowmesh/auth/AuthApplicationTests.java
Labels: 설정

#14 [#11] 회원가입 API 기능 추가
  com.jv-cc.flowmesh.auth/build.gradle
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/AuthDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/Error.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/UserExistEmailException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/UserExistNicknameException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/UserExistSlackidException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/UserExistUsernameException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/service/AuthService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/util/JwtUtil.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/repository/AuthRepository.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/AuthService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/infrastructor/configuration/PasswordConfig.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/AuthController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/SignupReqDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/response/ResDTO.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/response/SignupResDto.java
  com.jv-cc.flowmesh.auth/src/main/resources/application-dev.yml
  com.jv-cc.flowmesh.eureka-server/src/main/java/com/jv_cc/flowmesh/eureka_server/EurekaServerApplication.java
  http/auth.http
Labels: 기능

#12 [#6] feat: 허브 생성 기능 구현
  com.jv-cc.flowmesh.eureka-server/src/main/java/com/jv_cc/flowmesh/eureka_server/EurekaServerApplication.java
  com.jv-cc.flowmesh.hub-server/build.gradle
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/HubServerApplication.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/dto/HubDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/DuplicateHubCoordinatesException.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/DuplicateHubNameException.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/Error.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/model/HubEntity.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/repository/HubRepository.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/swagger/HubControllerSwagger.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/request/ReqHubPostDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/response/ResDTO.java
Labels: 기능

#15 [#13] 허브 수정 기능 구현
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/dto/HubDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/Error.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/NotFoundHubException.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/model/HubEntity.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/repository/HubRepository.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/swagger/HubControllerSwagger.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/response/ResHubDTO.java
Labels: 기능

#17 [#2] 로그인 API 구현
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/AuthDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/AuthTokenDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/AuthUserDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/UserMetaDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/Error.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/UserNotExistException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/UserPasswordMismatchException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/util/JwtUtil.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/repository/AuthRepository.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/AuthService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/AuthController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/SigninReqDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/response/SigninResDto.java
  http/auth.http
Labels: 기능

#20 [#16] feat: 허브 삭제 기능 구현
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/model/HubEntity.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/swagger/HubControllerSwagger.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
Labels: 기능

#22 [#21] 허브 단건 조회 기능 구현
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/dto/HubDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/Error.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/swagger/HubControllerSwagger.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/response/ResHubGetDTO.java
Labels: 기능

#24 [#19] feat: 토큰 재발급 API 구현
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/AuthInvalidTokenException.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/Error.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/util/JwtUtil.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/repository/AuthRepository.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/AuthService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/AuthController.java
  com.jv-cc.flowmesh.eureka-server/src/main/java/com/jv_cc/flowmesh/eureka_server/EurekaServerApplication.java
  http/auth.http
Labels: 기능

#27 [#18] feat: 사용자 정보 조회 API 구현
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/UserInfoDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/AuthController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/response/SigninResDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/response/UserResDto.java
  http/auth.http
Labels: 기능

#29 [#26] 업체 생성 기능 구현
  com.jv-cc.flowmesh.company/build.gradle
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/CompanyApplication.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/dto/CompanyDTO.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/DuplicateCompanyNameException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/Error.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/HubException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/NotFoundHubException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/service/CompanyService.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/domain/repository/CompanyRepository.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/infrastructure/HubClient.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/infrastructure/swagger/CompanyControllerSwagger.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/presentation/controller/CompanyController.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/presentation/request/ReqCompanyPostDTO.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/presentation/response/ResCompanyDTO.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/presentation/response/ResDTO.java
  com.jv-cc.flowmesh.hub-server/build.gradle
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/HubServerApplication.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/repository/HubRepository.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
Labels: 기능

#31 [#28] 사용자 정보 변경 API 구현
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/UserInfoDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/UserReqDto.java
  http/auth.http
Labels: 기능

#35 [#30] 업체 수정 기능 구현
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/Error.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/company/CompanyException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/company/DuplicateCompanyNameException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/company/NotFoundCompanyException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/hub/HubException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/exception/hub/NotFoundHubException.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/application/service/CompanyService.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/domain/model/CompanyEntity.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/domain/repository/CompanyRepository.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/infrastructure/swagger/CompanyControllerSwagger.java
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/presentation/controller/CompanyController.java
Labels: 기능

#44 [#34] 사용자 비활성화 기능 구현
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
  http/auth.http
Labels: 기능

#46 [#45] 사용자 권한 변경 기능 구현
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/RoleReqDto.java
  http/auth.http
Labels: 기능

#48 [#47] 사용자 검색 기능 구현
  com.jv-cc.flowmesh.auth/build.gradle
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/dto/UserInfoDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/repository/AuthRepository.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/infrastructor/constants/PageOrderType.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/infrastructor/constants/PageSortType.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/SearchReqDto.java
  com.jv-cc.flowmesh.auth/src/main/resources/application-dev.yml
  http/auth.http
Labels: 기능

#41 [#9]Order 서비스 환경 초기 설정 완료
  com.jv-cc.flowmesh.order-service/.gitattributes
  com.jv-cc.flowmesh.order-service/.gitignore
  com.jv-cc.flowmesh.order-service/build.gradle
  com.jv-cc.flowmesh.order-service/gradle/wrapper/gradle-wrapper.jar
  com.jv-cc.flowmesh.order-service/gradle/wrapper/gradle-wrapper.properties
  com.jv-cc.flowmesh.order-service/gradlew
  com.jv-cc.flowmesh.order-service/gradlew.bat
  com.jv-cc.flowmesh.order-service/settings.gradle
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/OrderServiceApplication.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/application/dto/OrderDTO.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/application/exception/Error.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/application/exception/OrderException.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/application/service/OrderService.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/domain/model/OrderEntity.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/domain/model/OrderStatusEnum.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/domain/repository/OrderRepository.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/infrastructure/swagger/OrderControllerSwagger.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/presentation/controller/OrderController.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/presentation/request/OrderRequestPostDTO.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/presentation/request/OrderRequestPutDTO.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/presentation/response/OrderResponseDTO.java
  com.jv-cc.flowmesh.order-service/src/main/java/com/jv_cc/flowmesh/order_service/presentation/response/ResponseDTO.java
  com.jv-cc.flowmesh.order-service/src/main/resources/application-dev.yml
  com.jv-cc.flowmesh.order-service/src/main/resources/application.yml
  com.jv-cc.flowmesh.order-service/src/test/java/com/jv_cc/flowmesh/order_service/OrderServiceApplicationTests.java
Labels: 설정

#43 [#7] Delivery Manager 서비스 환경 초기 설정 완료
  com.jv-cc.flowmesh.deliveryManager/.gitattributes
  com.jv-cc.flowmesh.deliveryManager/.gitignore
  com.jv-cc.flowmesh.deliveryManager/build.gradle
  com.jv-cc.flowmesh.deliveryManager/gradle/wrapper/gradle-wrapper.jar
  com.jv-cc.flowmesh.deliveryManager/gradle/wrapper/gradle-wrapper.properties
  com.jv-cc.flowmesh.deliveryManager/gradlew
  com.jv-cc.flowmesh.deliveryManager/gradlew.bat
  com.jv-cc.flowmesh.deliveryManager/settings.gradle
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/DeliverymanagerApplication.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/dto/DeliveryManagerDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/DeliveryManagerException.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/Error.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/service/DeliveryManagerService.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/model/DeliveryManagerEntity.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/model/DeliveryManagerEnum.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/repository/DeliveryManagerRepository.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/infrastructure/swagger/DeliveryManagerSwagger.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/controller/DeliveryManagerController.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/request/DeliveryManagerPostDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/response/DeliveryManagerResponseDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/response/ResponseDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/resources/application-dev.yml
  com.jv-cc.flowmesh.deliveryManager/src/main/resources/application.yml
Labels: 설정

#57 [#53] Auth 도메인 리팩토링
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/Auth.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/model/UserRoleEnum.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/AuthService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/AuthController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
Labels: 리팩토링

#62 [#56] 허브 권한 검증 로직 구현
  com.jv-cc.flowmesh.company/src/main/java/com/jv_cc/flowmesh/company/presentation/controller/CompanyController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/dto/HubDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/Error.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/exception/MasterOnlyAccessException.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/model/HubEntity.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/swagger/HubControllerSwagger.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/request/ReqHubPostDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/response/ResHubGetDTO.java
  com.jv-cc.flowmesh.product/src/main/java/com/jv_cc/flowmesh/product/presentation/controller/ProductController.java
Labels: 기능

#67 refactor: Auth 도메인 문서화 및 수정사항 반영
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/application/util/JwtUtil.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/domain/service/UserService.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/infrastructor/swagger/AuthControllerSwagger.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/SigninReqDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/SignupReqDto.java
  com.jv-cc.flowmesh.gateway-server/settings.gradle
  com.jv-cc.flowmesh.gateway/src/main/java/com/jv_cc/flowmesh/gateway/application/util/JwtUtil.java
Labels: 리팩토링

#72 [#71] README.md 작성
  README.md
Labels: 문서

#74 [#71] docs: 트러블 슈팅 링크 추가
  README.md
Labels: 문서

#70 [#64] 허브간 이동 정보 생성 기능 구현 및 허브 검색 기능 구현
  com.jv-cc.flowmesh.hub-server/build.gradle
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/dto/HMIDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HMIService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/application/service/HubService.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/model/HMIEntity.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/repository/HMIRepository.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/domain/repository/HubRepository.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/constants/PageOrderType.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/infrastructure/constants/PageSortType.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HMIController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/controller/HubController.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/request/ReqHMIPostDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/request/SearchReqDto.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/response/ResHMIDTO.java
  com.jv-cc.flowmesh.hub-server/src/main/java/com/jv_cc/flowmesh/hub_server/presentation/response/ResHubGetDTO.java
Labels: 기능

#75 [#69] User 도메인 및 수정사항 반영
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/infrastructor/swagger/UserControllerSwagger.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/controller/UserController.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/RoleReqDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/SearchReqDto.java
  com.jv-cc.flowmesh.auth/src/main/java/com/jv_cc/flowmesh/auth/presentation/request/UserReqDto.java
  http/auth.http
Labels: 리팩토링

#54 [#54] feature: 배송 담당자 생성 기능 구현
  com.jv-cc.flowmesh.deliveryManager/.gitignore
  com.jv-cc.flowmesh.deliveryManager/build.gradle
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/DeliverymanagerApplication.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/dto/DeliveryManagerCreateDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/dto/DeliveryManagerDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/dto/DeliveryManagerPutDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/Error.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/ExceededCapacityException.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/NotFoundDeliveryManagerException.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/NotFoundDeliveryManagerTypeException.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/NotFoundHubException.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/exception/NotPermissionException.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/application/service/DeliveryManagerService.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/model/DeliveryManagerEntity.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/model/DeliveryManagerEnum.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/model/UserRoleEnum.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/repository/DeliveryManagerRepository.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/domain/service/DeliveryManagerService.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/infrastructure/feignclient/AuthClient.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/infrastructure/feignclient/HubClient.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/infrastructure/swagger/DeliveryManagerSwagger.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/controller/DeliveryManagerController.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/request/DeliveryManagerPostDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/request/DeliveryManagerPostRequestDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/request/DeliveryManagerPutRequestDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/response/DeliveryManagerGetOneResponseDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/response/DeliveryManagerPostResponseDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/response/DeliveryManagerPutResponseDTO.java
  com.jv-cc.flowmesh.deliveryManager/src/main/java/com/jv_cc/flowmesh/deliverymanager/presentation/response/DeliveryManagerResponseDTO.java
Labels: 기능

#55 [#3] feat: 배송 초기 세팅
  com.jv-cc.flowmesh.delivery/.gitattributes
  com.jv-cc.flowmesh.delivery/.gitignore
  com.jv-cc.flowmesh.delivery/build.gradle
  com.jv-cc.flowmesh.delivery/gradle/wrapper/gradle-wrapper.jar
  com.jv-cc.flowmesh.delivery/gradle/wrapper/gradle-wrapper.properties
  com.jv-cc.flowmesh.delivery/gradlew
  com.jv-cc.flowmesh.delivery/gradlew.bat
  com.jv-cc.flowmesh.delivery/settings.gradle
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/DeliveryApplication.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/dto/DeliveryCreateDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/dto/DeliveryDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/dto/DeliveryDeleteDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/dto/DeliveryPutDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/exception/CommonExceptionHandler.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/exception/DeliveryException.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/exception/Error.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/exception/NotCreatedDeliveryException.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/application/exception/NotDeletedException.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/domain/model/DeliveryEntity.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/domain/model/DeliveryEnum.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/domain/model/DeliveryRouteEntity.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/domain/repository/DeliveryRepository.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/domain/repository/DeliveryRouteRepository.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/domain/service/DeliveryService.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/infrastructure/feignclient/AiClient.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/infrastructure/feignclient/HubClient.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/infrastructure/swagger/DeliverySwagger.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/controller/DeliveryController.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/request/DeliveryPostRequestDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/request/DeliveryPutRequestDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryAllGetResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryDeleteResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryGetResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryPostResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryPutResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/DeliveryResponseDTOForHub.java
  com.jv-cc.flowmesh.delivery/src/main/java/com/jv_cc/flowmesh/delivery/presentation/response/ResponseDTO.java
  com.jv-cc.flowmesh.delivery/src/main/resources/application-dev.yml
  com.jv-cc.flowmesh.delivery/src/main/resources/application.yml
  com.jv-cc.flowmesh.delivery/src/test/java/com/jv_cc/flowmesh/delivery/DeliveryApplicationTests.java
Labels: 설정
